### ISSUE TITLE
singular and plural field names aren't normalized

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql-custom-post-type-ui#10]
If I add a single name of `team mate`, it's registered to the schema like that. Ideally these fields would be normalized to camelcase automatically. so `team mate` becomes `teamMate`.

It could be nice to have an option to infer the field names from the post type labels too. `Team Mate` could become `teamMate` automatically.

**Comment by TylerBarnes** [comment]
If I use `TeamMate`, it is normalized to `teamMate` though

**Comment by jasonbahl** [comment]
@TylerBarnes I wouldn't mind doing this in the UI of this plugin via JavaScript to suggest a name, but we _don't_ want WPGraphQL to do this behind the scenes since labels are translated and we don't want Types and Fields in the Schema to be translated.

**Comment by TylerBarnes** [comment]
Ah, makes sense! No inferred field names from labels. How about camelcasing field names with spaces?

**Comment by jasonbahl** [comment]
Camel Casing _should_ already be happening, but I'll check it out.

**Comment by TylerBarnes** [comment]
It's not doing it currently, it will add it to the schema with spaces like
```graphql
{
	team Mate {
		...
 	}
}
```

**Comment by jasonbahl** [comment]
@TylerBarnes this is addressed in the v1.2.0 release. 

https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/pull/16/files#diff-5cf0f43eb7881516f027acf7b1784defe9675b3fbf483c15a562859aa0597ca6R142-R143
