### ISSUE TITLE
Field names fields should be required

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql-custom-post-type-ui#11]
Currently these are not required. This leads to an odd UX.

If you add a new post type with no intention of using it in WPGraphQL, it will still be set to `"show_in_graphql" => true` by default. This means when you create your new post type, without changing any settings related to this plugin, you'll get an error when attempting to make a gql request.

Ideally these fields should be required. I went to start making a PR to do this, but I realized these fields should only be required if "Show in GraphQL" is set to true. If it's false these fields shouldn't be required. I'm not too sure how to make that work with the CPTUI `$ui` helper without adding some custom JS 🤔 .

Do we need to register a little bit of JS that flips these between required and not-required?

**Comment by jasonbahl** [comment]
👋  I just published [v1.2.0](https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/releases/tag/v1.2.0) which makes some updates to the GraphQL Settings form. 

The `graphql_single_name` and `graphql_plural_name` fields are now conditional based on the `show_in_graphql` field. If `show_in_graphql` is false, those fields are hidden. If true, these fields show and are set as required.

![show-in-graphql-cptui](https://user-images.githubusercontent.com/1260765/112374090-4b8eaa00-8ca7-11eb-8ca3-20320493a152.gif)
