### ISSUE TITLE
Won't change to True

### ISSUE THREAD

**Issue by ashleynexvelsolutions** [wp-graphql/wp-graphql-custom-post-type-ui#17]
Hey there,
In CPT UI I can't get "Show in GraphQL" to save as true. I thought it might be something in my config or settings so I spun up a fresh WordPress install and installed the latest versions of WPGraphQL (version 1.3.3), CPT UI (version 1.8.2), and this plugin (version 1.2.0). Everything's just set to their defaults.  I added a new custom post type in CPT UI with the Post Type Slug being case_results, the Plural Label being Case Results, and the Singular Label being Case Result. Everything else is left untouched. When I select True in Show in GraphQL it seems to automatically pull in what's in Singular Label for GraphQL Single Name and Plural Label for GraphQL Plural Name. So I did try that first. But when I hit Save Post Type it just goes back to false. I tried changing the GraphQL Single Name to various different things including case-result, caseresult, and _caseresult and tried changing the GraphQL Plural Name to case-results, caseresults, and _caseresults but none worked. When I go to Registered Types/Taxes below is what I see in the Settings column. Any help would be much appreciated. 

name: case_results
label: Case Results
singular_label: Case Result
description: ""
public: true
publicly_queryable: true
show_ui: true
show_in_nav_menus: true
delete_with_user: false
show_in_rest: true
rest_base: ""
rest_controller_class: ""
has_archive: false
has_archive_string: ""
exclude_from_search: false
capability_type: post
hierarchical: false
rewrite: true
rewrite_slug: ""
rewrite_withfront: true
query_var: true
query_var_slug: ""
menu_position: ""
show_in_menu: true
show_in_menu_string: ""
menu_icon: ""
custom_supports: ""
graphql_single_name: ""
graphql_plural_name: ""

Actually I pulled an older version of this plugin off of another site we're using it on, version 1.1, and that one seems to be working as expected.

**Comment by Rame0ne** [comment]
👍

**Comment by shossk** [comment]
👍

**Comment by anthonyrenard** [comment]
Got the same issue

**Comment by frstphn** [comment]
Got the same issue. V1.1 is working as expected.

**Comment by sonyarianto** [comment]
another "got the same issue"

**Comment by sonyarianto** [comment]
I can figure it out by hacking to `wp_options` field on `option_name` = `cptui_post_types` like this.

```
s:15:"show_in_graphql";s:4:"true";s:19:"graphql_single_name";s:8:"property";s:19:"graphql_plural_name";s:10:"properties"
```

but I don't have time to check on the source code

**Comment by jasonbahl** [comment]
uh oh! 

Custom Post Type UI just release v1.9.0 which adds formal support for WPGraphQL to the core plugin, so you will no longer need this "bridge" plugin. 

I'd recommend updating Custom Post Type UI to v1.9.0+ and de-activating this plugin.

Let's be sure to check that this issue is not happening over there too! I'm Going to test right now.

**Comment by jasonbahl** [comment]
I've tested Custom Post Type UI v1.9.0 with this plugin de-activated, and things are working as expected. 

I'd recommend upgrading and de-activating this plugin. 

If the issue still exists with Custom Post Type UI v1.9.0, I'd recommend opening an issue on the CPT UI repo: https://github.com/WebDevStudios/custom-post-type-ui, and reference this issue and mention me and I'll dig in further, but so far, things are working 👌  for me on v1.9.0.

**Comment by sonyarianto** [comment]
@jasonbahl yeah, I just saw it today and the v1.9.0 solved everything :) getting better and better.

**Comment by ashleynexvelsolutions** [comment]
It works. Thanks @jasonbahl
