### ISSUE TITLE
Custom Taxonomy support

### ISSUE THREAD

**Issue by BartoszLobejko** [wp-graphql/wp-graphql-custom-post-type-ui#6]
Thanks for this simple but handy plugin.

It would be great to have taxonomy support. This way we could build really awesome stuff!

Regards

**Comment by elvismdev** [comment]
I second this, any update about supporting custom taxonomies we register from CPT-UI?

**Comment by henrikwirth** [comment]
Find my PR here: #7

**Comment by lai32290** [comment]
I extracted the code change from @henrikwirth 's PR [to a plugin](https://github.com/lai32290/wp-graphql-custom-post-type-ui-taxonomy-polyfil).
All the credits for @henrikwirth  please. Thanks for your help.

**Comment by jasonbahl** [comment]
closed by #7
