### ISSUE TITLE
Error when adding a new post type

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql-custom-post-type-ui#9]
When adding a new post type in CPTUI, if I don't scroll down and add the GraphQL single and plural names, but I create the post type, the site will be broken and the admin will be unreachable and display `The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.`

```
[30-Oct-2019 04:33:50 UTC] PHP Fatal error:  Uncaught GraphQL\Error\UserError: The much post_type isn't configured properly to show in GraphQL. It needs a "graphql_single_name" and a "graphql_plural_name" in /Users/tyler/Local Sites/wpgraphql/app/public/wp-content/plugins/wp-graphql/wp-graphql.php:415
Stack trace:
#0 [internal function]: WPGraphQL::{closure}('much')
#1 /Users/tyler/Local Sites/wpgraphql/app/public/wp-content/plugins/wp-graphql/wp-graphql.php(424): array_map(Object(Closure), Array)
#2 /Users/tyler/Local Sites/wpgraphql/app/public/wp-content/plugins/wp-graphql/wp-graphql.php(289): WPGraphQL::get_allowed_post_types()
#3 /Users/tyler/Local Sites/wpgraphql/app/public/wp-includes/class-wp-hook.php(286): WPGraphQL->get_allowed_types('')
#4 /Users/tyler/Local Sites/wpgraphql/app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /Users/tyler/Local Sites/wpgraphql/app/public/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#6 /Users/tyler/Local Sites/wpgraphql/app/public/wp-settings.php(525): do_action('init' in /Users/tyler/Local Sites/wpgraphql/app/public/wp-content/
```

**Comment by tomhermans** [comment]
Same issue here,
Was just following along https://www.youtube.com/watch?v=ZRQ94PMNEcg (around 2mins) ..


`Fatal error: Uncaught GraphQL\Error\UserError: The form_submission post_type isn't configured properly to show in GraphQL. It needs a "graphql_single_name" and a "graphql_plural_name" in /app/public/wp-content/plugins/wp-graphql/wp-graphql.php:411 
Stack trace: 
#0 [internal function]: WPGraphQL::{closure}('form_submission') 
#1 /app/public/wp-content/plugins/wp-graphql/wp-graphql.php(420): array_map(Object(Closure), Array) 
#2 /app/public/wp-content/plugins/wp-graphql/wp-graphql.php(287): WPGraphQL::get_allowed_post_types() 
#3 /app/public/wp-includes/class-wp-hook.php(288): WPGraphQL->get_allowed_types('') 
#4 /app/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) 
#5 /app/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
#6 /app/public/wp-settings.php(523): do_action('init') 
#7 /app/public/wp-config.php(76): require_once('/app/public/wp-...') 
#8 /app/public/wp-load.php(37): require_once('/app/public/wp-...') 
#9 /app/public/wp-blog-header.php(13): require_once('/app/public/wp-...') 
#10 in /app/public/wp-content/plugins/wp-graphql/wp-graphql.php on line 411`

**Comment by jasonbahl** [comment]
Ok, I've got this resolved. It turns out, there's a bit of a bug in WPGraphQL core that is trying to bootstrap Post Types that show in GraphQL too early, and if you have `GRAPHQL_DEBUG` enabled it's throwing an exception, even in non-graphql requests. 

I've got a PR to fix this in the core WPGraphQL plugin.

**Comment by jasonbahl** [comment]
Created an issue in the main WPGraphQL repo, as the change will happen there. 

https://github.com/wp-graphql/wp-graphql/issues/1043
